import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const font = Onest({ subsets: ["latin"], weight: ["300", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${font.className} bg-slate-600`}>
        {children}
      </body>
    </html>
  );
}
